#!/usr/bin/env python3
"""Convert selected Inter TTF files into compact 1-bit C++ bitmap fonts.

The generated files are intentionally simple and match the lightweight drawing
code in firmware/src/gfx/gfx.cpp. Coordinates use top-left text placement; the
converter stores per-glyph baseline offsets so descenders and punctuation keep
their natural alignment.
"""

from __future__ import annotations

from pathlib import Path
from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[1]
FONT_DIR = ROOT / "tools" / "fonts" / "Inter"
OUT_H = ROOT / "src" / "gfx" / "font_inter.h"
OUT_CPP = ROOT / "src" / "gfx" / "font_inter.cpp"

ASCII_FIRST = 0x20
ASCII_LAST = 0x7E
CHARS = [chr(c) for c in range(ASCII_FIRST, ASCII_LAST + 1)]

SPECS = [
    ("FontInterRegular11", "Inter-18pt-Regular.ttf", 11),
    ("FontInterRegular14", "Inter-24pt-Regular.ttf", 14),
    ("FontInterSemiBold18", "Inter-24pt-SemiBold.ttf", 18),
    ("FontInterBold28", "Inter-24pt-Bold.ttf", 28),
]


def pack_glyph(font: ImageFont.FreeTypeFont, ch: str, ascent: int) -> tuple[dict, list[int]]:
    # Bounding box relative to left-baseline anchor.
    bbox = font.getbbox(ch, anchor="ls")
    x0, y0, x1, y1 = bbox
    w = max(0, x1 - x0)
    h = max(0, y1 - y0)
    advance = int(round(font.getlength(ch)))
    if advance <= 0:
        advance = max(1, w)

    if w == 0 or h == 0:
        return {
            "width": 0,
            "height": 0,
            "xAdvance": advance,
            "xOffset": 0,
            "yOffset": 0,
        }, []

    img = Image.new("L", (w, h), 0)
    draw = ImageDraw.Draw(img)
    # Place the glyph baseline so its bbox lands at (0, 0).
    draw.text((-x0, -y0), ch, font=font, fill=255, anchor="ls")

    rows = []
    bytes_per_row = (w + 7) // 8
    pix = img.load()
    for y in range(h):
        for bx in range(bytes_per_row):
            b = 0
            for bit in range(8):
                x = bx * 8 + bit
                if x < w and pix[x, y] >= 96:
                    b |= 0x80 >> bit
            rows.append(b)

    return {
        "width": w,
        "height": h,
        "xAdvance": advance,
        "xOffset": x0,
        "yOffset": y0,
    }, rows


def emit_array(name: str, values: list[int], per_line: int = 16) -> str:
    lines = [f"const uint8_t {name}[] PROGMEM = {{"]
    for i in range(0, len(values), per_line):
        chunk = values[i : i + per_line]
        lines.append("    " + ",".join(f"0x{v:02X}" for v in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def convert_font(symbol: str, font_file: str, size: int) -> tuple[str, str, int]:
    font = ImageFont.truetype(str(FONT_DIR / font_file), size=size)
    ascent, descent = font.getmetrics()
    y_advance = ascent + descent

    bitmap: list[int] = []
    glyphs: list[dict] = []
    for ch in CHARS:
        offset = len(bitmap)
        meta, data = pack_glyph(font, ch, ascent)
        bitmap.extend(data)
        meta["bitmapOffset"] = offset
        glyphs.append(meta)

    bitmap_name = f"{symbol}Bitmaps"
    glyph_name = f"{symbol}Glyphs"

    cpp_parts = [emit_array(bitmap_name, bitmap)]
    cpp_parts.append(f"const EInkGlyph {glyph_name}[] PROGMEM = {{")
    for meta in glyphs:
        cpp_parts.append(
            "    "
            f"{{{meta['bitmapOffset']}, {meta['width']}, {meta['height']}, "
            f"{meta['xAdvance']}, {meta['xOffset']}, {meta['yOffset']}}},"
        )
    cpp_parts.append("};")
    cpp_parts.append(
        f"const EInkFont {symbol} PROGMEM = "
        f"{{{bitmap_name}, {glyph_name}, {ASCII_FIRST}, {ASCII_LAST}, "
        f"{y_advance}, {ascent}, \"{symbol}\"}};"
    )

    h_decl = f"extern const EInkFont {symbol};"
    return "\n\n".join(cpp_parts), h_decl, len(bitmap)


def main() -> None:
    missing = [f for _, f, _ in SPECS if not (FONT_DIR / f).exists()]
    if missing:
        raise SystemExit(f"Missing font files: {missing}")

    h_lines = [
        "#ifndef EINK_FONT_INTER_H",
        "#define EINK_FONT_INTER_H",
        "",
        "#include \"gfx.h\"",
        "",
        "// Generated by firmware/tools/convert_inter_font.py",
    ]
    cpp_lines = [
        "#include \"font_inter.h\"",
        "#include <Arduino.h>",
        "",
        "// Generated by firmware/tools/convert_inter_font.py",
    ]

    total = 0
    for symbol, font_file, size in SPECS:
        cpp, decl, nbytes = convert_font(symbol, font_file, size)
        h_lines.append(decl)
        cpp_lines.append(cpp)
        total += nbytes

    h_lines.extend(["", "#endif // EINK_FONT_INTER_H", ""])
    cpp_lines.append("")

    OUT_H.write_text("\n".join(h_lines), encoding="utf-8")
    OUT_CPP.write_text("\n\n".join(cpp_lines), encoding="utf-8")
    print(f"Wrote {OUT_H.relative_to(ROOT)}")
    print(f"Wrote {OUT_CPP.relative_to(ROOT)}")
    print(f"Bitmap payload: {total} bytes across {len(SPECS)} fonts")


if __name__ == "__main__":
    main()
