#!/usr/bin/env python3
"""Convert STHeiti Medium TTC into 12pt C bitmap font for Chinese characters.

Usage:
    cd firmware
    python3 tools/convert_cn_font.py

To add more characters, edit CHARS below and re-run.
"""

from __future__ import annotations

from pathlib import Path
from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[1]
FONT_DIR = ROOT / "tools" / "fonts"
OUT_H = ROOT / "src" / "gfx" / "font_cn.h"
OUT_CPP = ROOT / "src" / "gfx" / "font_cn.cpp"

FONT_FILE = "STHeiti Medium.ttc"
SIZE = 12

# Characters to include. Edit this string to add more, then re-run.
CHARS = "周一二三四五六日上下午月"


def pack_glyph(font: ImageFont.FreeTypeFont, ch: str, ascent: int) -> tuple[dict, list[int]]:
    bbox = font.getbbox(ch, anchor="ls")
    x0, y0, x1, y1 = bbox
    w = max(0, x1 - x0)
    h = max(0, y1 - y0)
    advance = int(round(font.getlength(ch)))
    if advance <= 0:
        advance = max(1, w)

    if w == 0 or h == 0:
        return {
            "width": 0, "height": 0,
            "xAdvance": advance, "xOffset": 0, "yOffset": 0,
        }, []

    img = Image.new("L", (w, h), 0)
    draw = ImageDraw.Draw(img)
    draw.text((-x0, -y0), ch, font=font, fill=255, anchor="ls")

    rows = []
    bytes_per_row = (w + 7) // 8
    pix = img.load()
    for y in range(h):
        for bx in range(bytes_per_row):
            b = 0
            for bit in range(8):
                x = bx * 8 + bit
                if x < w and pix[x, y] >= 96:
                    b |= 0x80 >> bit
            rows.append(b)

    return {
        "width": w, "height": h,
        "xAdvance": advance, "xOffset": x0, "yOffset": y0,
    }, rows


def emit_array(name: str, values: list[int], per_line: int = 16) -> str:
    lines = [f"const uint8_t {name}[] PROGMEM = {{"]
    for i in range(0, len(values), per_line):
        chunk = values[i : i + per_line]
        lines.append("    " + ",".join(f"0x{v:02X}" for v in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def main() -> None:
    font_path = FONT_DIR / FONT_FILE
    if not font_path.exists():
        raise SystemExit(f"Missing: {font_path}")

    font = ImageFont.truetype(str(font_path), size=SIZE)
    ascent, descent = font.getmetrics()
    y_advance = ascent + descent

    bitmap: list[int] = []
    glyphs: list[dict] = []

    for ch in CHARS:
        offset = len(bitmap)
        meta, data = pack_glyph(font, ch, ascent)
        bitmap.extend(data)
        meta["bitmapOffset"] = offset
        glyphs.append(meta)

    # UTF-8 encoded character set string for C
    cn_chars_c = "".join(f"\\u{ord(c):04X}" for c in CHARS)

    # ── Generate .h ──
    h_lines = [
        "#ifndef EINK_FONT_CN_H",
        "#define EINK_FONT_CN_H",
        "",
        '#include "gfx.h"',
        "",
        "// Generated by firmware/tools/convert_cn_font.py",
        f"// Characters ({len(CHARS)}): {CHARS}",
        "// To add characters: edit CHARS in convert_cn_font.py and re-run",
        "",
        "struct CNFont {",
        "    const uint8_t *bitmap;",
        "    const EInkGlyph *glyphs;",
        "    int charCount;",
        "    uint8_t yAdvance;",
        "    uint8_t ascent;",
        "    const char *name;",
        "};",
        "",
        f"extern const CNFont FontCN12;",
        "",
        "// Find glyph index for a UTF-8 character, returns -1 if not found",
        "int cnCharIndex(const char *utf8);",
        "",
        "// Draw Chinese text (set pixels in imgBuf)",
        "void drawCnFontText(const CNFont &font, const char *msg, int x, int y);",
        "// Draw Chinese text clearing both buffers (white text on colored bg)",
        "void drawCnFontTextClearRed(const CNFont &font, const char *msg, int x, int y);",
        "// Calculate text pixel width",
        "int cnFontTextWidth(const CNFont &font, const char *msg);",
        "",
        "#endif // EINK_FONT_CN_H",
        "",
    ]
    OUT_H.write_text("\n".join(h_lines), encoding="utf-8")

    # ── Generate .cpp ──
    cpp_parts = [
        '#include "font_cn.h"',
        '#include "config.h"',
        '#include <Arduino.h>',
        '#include <string.h>',
        "",
        "// Generated by firmware/tools/convert_cn_font.py",
        "",
        f'// Character set: {CHARS}',
        f"const char CN_CHARS[] = \"{cn_chars_c}\";",
        f"const int CN_CHAR_COUNT = {len(CHARS)};",
        "",
        emit_array("FontCN12Bitmaps", bitmap),
        "",
        f"const EInkGlyph FontCN12Glyphs[] PROGMEM = {{",
    ]
    for m in glyphs:
        cpp_parts.append(
            f"    {{{m['bitmapOffset']}, {m['width']}, {m['height']}, "
            f"{m['xAdvance']}, {m['xOffset']}, {m['yOffset']}}},"
        )
    cpp_parts.append("};")
    cpp_parts.append("")
    cpp_parts.append(
        f"const CNFont FontCN12 PROGMEM = "
        f"{{FontCN12Bitmaps, FontCN12Glyphs, {len(CHARS)}, "
        f"{y_advance}, {ascent}, \"CN12\"}};"
    )
    cpp_parts.append("")
    cpp_parts.append("// ── Lookup ──")
    cpp_parts.append("")
    cpp_parts.append("int cnCharIndex(const char *utf8) {")
    cpp_parts.append("    for (int i = 0; i < CN_CHAR_COUNT; i++) {")
    cpp_parts.append("        if (memcmp(utf8, &CN_CHARS[i * 3], 3) == 0) return i;")
    cpp_parts.append("    }")
    cpp_parts.append("    return -1;")
    cpp_parts.append("}")
    cpp_parts.append("")
    cpp_parts.append("// ── Drawing ──")
    cpp_parts.append("")
    cpp_parts.append(
        "static void drawCnGlyph(uint8_t *buf, const CNFont &font, "
        "int idx, int x, int y, bool set) {"
    )
    cpp_parts.append("    const EInkGlyph &g = font.glyphs[idx];")
    cpp_parts.append("    if (g.width == 0 || g.height == 0) return;")
    cpp_parts.append("    const uint8_t *bmp = font.bitmap + g.bitmapOffset;")
    cpp_parts.append("    int bpr = (g.width + 7) / 8;")
    cpp_parts.append("    int gx = x + g.xOffset;")
    cpp_parts.append("    int gy = y + font.ascent + g.yOffset;")
    cpp_parts.append("    for (int row = 0; row < g.height; row++) {")
    cpp_parts.append("        for (int col = 0; col < g.width; col++) {")
    cpp_parts.append("            uint8_t b = bmp[row * bpr + col / 8];")
    cpp_parts.append("            if (b & (0x80 >> (col % 8))) {")
    cpp_parts.append("                if (set) setPixelBuf(buf, gx + col, gy + row);")
    cpp_parts.append("                else     clearPixelBuf(buf, gx + col, gy + row);")
    cpp_parts.append("            }")
    cpp_parts.append("        }")
    cpp_parts.append("    }")
    cpp_parts.append("}")
    cpp_parts.append("")
    cpp_parts.append("void drawCnFontText(const CNFont &font, const char *msg, int x, int y) {")
    cpp_parts.append("    int cx = x, i = 0;")
    cpp_parts.append("    while (msg[i]) {")
    cpp_parts.append("        int idx = cnCharIndex(&msg[i]);")
    cpp_parts.append("        if (idx >= 0) {")
    cpp_parts.append("            drawCnGlyph(imgBuf, font, idx, cx, y, true);")
    cpp_parts.append("            cx += font.glyphs[idx].xAdvance;")
    cpp_parts.append("            i += 3;")
    cpp_parts.append("        } else { i++; }")
    cpp_parts.append("    }")
    cpp_parts.append("}")
    cpp_parts.append("")
    cpp_parts.append(
        "void drawCnFontTextClearRed(const CNFont &font, const char *msg, int x, int y) {"
    )
    cpp_parts.append("    int cx = x, i = 0;")
    cpp_parts.append("    while (msg[i]) {")
    cpp_parts.append("        int idx = cnCharIndex(&msg[i]);")
    cpp_parts.append("        if (idx >= 0) {")
    cpp_parts.append("            drawCnGlyph(imgBuf, font, idx, cx, y, false);")
    cpp_parts.append("            drawCnGlyph(redBuf, font, idx, cx, y, false);")
    cpp_parts.append("            cx += font.glyphs[idx].xAdvance;")
    cpp_parts.append("            i += 3;")
    cpp_parts.append("        } else { i++; }")
    cpp_parts.append("    }")
    cpp_parts.append("}")
    cpp_parts.append("")
    cpp_parts.append("int cnFontTextWidth(const CNFont &font, const char *msg) {")
    cpp_parts.append("    int w = 0, i = 0;")
    cpp_parts.append("    while (msg[i]) {")
    cpp_parts.append("        int idx = cnCharIndex(&msg[i]);")
    cpp_parts.append("        if (idx >= 0) { w += font.glyphs[idx].xAdvance; i += 3; }")
    cpp_parts.append("        else { i++; }")
    cpp_parts.append("    }")
    cpp_parts.append("    return w;")
    cpp_parts.append("}")
    cpp_parts.append("")

    OUT_CPP.write_text("\n".join(cpp_parts), encoding="utf-8")

    print(f"Wrote {OUT_H.relative_to(ROOT)}")
    print(f"Wrote {OUT_CPP.relative_to(ROOT)}")
    print(f"Characters ({len(CHARS)}): {CHARS}")
    print(f"Bitmap payload: {len(bitmap)} bytes")


if __name__ == "__main__":
    main()
