Import("env")
import os
import subprocess
from datetime import datetime

def git_output(args):
    project_dir = env.subst("$PROJECT_DIR")
    try:
        return subprocess.check_output(
            ["git", "-C", project_dir] + args,
            stderr=subprocess.DEVNULL,
        ).decode("utf-8").strip()
    except Exception:
        return ""

git_sha = git_output(["rev-parse", "--short=7", "HEAD"])
git_tag = git_output(["describe", "--tags", "--exact-match", "HEAD"])
dirty = bool(git_output(["status", "--porcelain"]))

local_version = "local-" + datetime.now().strftime("%Y%m%d-%H%M")

if dirty:
    firmware_version = local_version
elif git_tag:
    firmware_version = git_tag
elif git_sha:
    firmware_version = "g" + git_sha
else:
    firmware_version = local_version

version_header = os.path.join(env.subst("$PROJECT_DIR"), "src", "firmware_version.h")
with open(version_header, "w", encoding="utf-8") as f:
    f.write("// Generated by firmware/merge_firmware.py. Do not edit.\n")
    f.write("#ifndef EINK_FIRMWARE_VERSION_H\n")
    f.write("#define EINK_FIRMWARE_VERSION_H\n\n")
    f.write(f'#define FIRMWARE_VERSION "{firmware_version}"\n\n')
    f.write("#endif // EINK_FIRMWARE_VERSION_H\n")

print(f"Firmware version: {firmware_version}")

def merge_bin(source, target, env):
    firmware = str(target[0])
    board = env.BoardConfig()
    mcu = board.get("build.mcu", "esp32")
    flash_mode = "dio"
    flash_freq = board.get("build.f_flash", "40000000L").replace("L", "")
    flash_freq_m = str(int(int(flash_freq) / 1000000)) + "m"
    flash_size = board.get("upload.flash_size", "4MB")

    esptool = os.path.join(
        env.PioPlatform().get_package_dir("tool-esptoolpy") or "",
        "esptool.py",
    )
    output = os.path.join(env.subst("$BUILD_DIR"), "firmware_merged.bin")

    extra = env.get("FLASH_EXTRA_IMAGES", [])
    print("=== FLASH_EXTRA_IMAGES ===")
    for offset, path in extra:
        print(f"  {offset} -> {env.subst(path)}")
    print(f"  APP -> 0x10000 {firmware}")
    print("==========================")

    cmd = [
        "$PYTHONEXE", esptool,
        "--chip", mcu,
        "merge_bin",
        "--flash_mode", flash_mode,
        "--flash_freq", flash_freq_m,
        "--flash_size", flash_size,
        "-o", output,
    ]

    for offset, path in extra:
        cmd.extend([offset, env.subst(path)])

    cmd.extend(["0x10000", firmware])

    env.Execute(env.VerboseAction(" ".join(cmd), "Merging firmware into single binary"))

env.AddPostAction("$BUILD_DIR/${PROGNAME}.bin", merge_bin)
