; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = wft0420cz15

[common]
platform = espressif32
framework = arduino
board = esp32-c3-devkitm-1
monitor_speed = 115200
board_build.partitions = min_spiffs.csv
build_src_filter =
	+<*>
	-<gfx/>
	-<epd/>
extra_scripts = merge_firmware.py
lib_deps =
	bblanchon/ArduinoJson@^7.0
	zinggjm/GxEPD2@^1.6.9

[env:wft0420cz15]
extends = common
build_flags = 
	-DDISPLAY_WFT0420CZ15
	-DEPD_WIDTH=400 -DEPD_HEIGHT=300
	-DARDUINO_USB_MODE=1 -DARDUINO_USB_CDC_ON_BOOT=1

[env:gdey042t81]	
extends = common
build_flags = 
	-DDISPLAY_GDEY042T81
	-DEPD_WIDTH=400 -DEPD_HEIGHT=300
	-DARDUINO_USB_MODE=1 -DARDUINO_USB_CDC_ON_BOOT=1
